// recipes-items.js
window.recipes = {
  "Spring Roll": {
    title: "Spring Roll",
    image: "../IMG/f1.jpg",
    description:
      "Chop all vegetables into thin slices. Cook and slice the shrimp or chicken. Soak the vermicelli noodles in hot water until soft, then drain.",
    ingredients: [
      "Vegetables",
      "Shrimp or Chicken",
      "Vermicelli noodles",
      "Rice paper",
    ],
    steps: ["Chop vegetables", "Cook meat", "Soak noodles", "Assemble roll"],
    video: "https://www.youtube.com/embed/wNB05Zc4TqA",
  },
  "Fish Fry": {
    title: "Fish Fry",
    image: "../IMG/f2.jpg",
    description: "Fry fish with spices and herbs for a crispy, flavorful dish.",
    ingredients: ["Fish", "Spices", "Herbs", "Oil"],
    steps: ["Marinate fish", "Heat oil", "Fry fish", "Serve hot"],
    video: "https://www.youtube.com/embed/to-Tiwl34RE",
  },
  "Bread Omelette": {
    title: "Bread Omelette",
    image: "../IMG/f3.jpg",
    description:
      "Bread Omelette is a quick and easy breakfast recipe that combines the goodness of bread with the protein-rich omelette. It’s perfect for a wholesome meal on the go or a light snack.",
    ingredients: [
      "2 slices of bread",
      "2 eggs",
      "1 small onion (finely chopped)",
      "1 small tomato (finely chopped)",
      "1 green chili (finely chopped)",
      "2 tablespoons of milk",
      "Salt to taste",
      "Black pepper to taste",
      "1 tablespoon of butter or oil",
      "Fresh coriander leaves (finely chopped, optional)",
    ],
    steps: [
      "In a mixing bowl, crack the eggs and add the milk.",
      "Add chopped onion, tomato, green chili, salt, and black pepper. Mix well.",
      "Heat a non-stick pan on medium heat and add butter or oil.",
      "Pour the egg mixture into the pan, spreading it evenly.",
      "Let it cook for 1-2 minutes until the edges start to set.",
      "Place the slices of bread on the omelette and press down slightly to soak the bread in the egg mixture.",
      "Let it cook for another minute.",
      "Carefully flip the omelette with the bread slices attached and cook the other side until golden brown.",
      "Once done, remove from the pan, and serve hot with your favorite sauce or chutney.",
    ],
    video: "https://www.youtube.com/embed/9jaC5_9mMqw",
  },
  "Fish Bread": {
    title: "Fish Bread",
    image: "../IMG/f4.jpg",
    description:
      "Fish Bread is a delicious fusion dish that combines the flavors of seasoned fish with crispy bread. It's a unique and tasty snack or appetizer that's easy to prepare and perfect for seafood lovers.",
    ingredients: [
      "4 slices of bread",
      "200g of fish fillet (boneless and skinless)",
      "1 small onion (finely chopped)",
      "1 small tomato (finely chopped)",
      "1 green chili (finely chopped)",
      "1 teaspoon of ginger-garlic paste",
      "1/2 teaspoon of turmeric powder",
      "1/2 teaspoon of red chili powder",
      "Salt to taste",
      "1 tablespoon of lemon juice",
      "Fresh coriander leaves (finely chopped)",
      "2 tablespoons of butter or oil",
      "1 egg (beaten)",
    ],
    steps: [
      "Heat oil in a pan and add the chopped onion, tomato, green chili, and ginger-garlic paste. Sauté until the onions turn golden brown.",
      "Add the turmeric powder, red chili powder, and salt. Mix well.",
      "Add the fish fillet to the pan and cook until the fish is done. Use a fork to break the fish into small pieces as it cooks.",
      "Once cooked, add lemon juice and chopped coriander leaves. Mix well and set aside.",
      "Take the bread slices and lightly toast them on both sides in a pan until they are slightly crisp.",
      "Brush one side of each bread slice with beaten egg.",
      "Place a generous amount of the fish filling on the egg-brushed side of two bread slices.",
      "Cover each with another slice of bread (egg-brushed side down), pressing gently to secure.",
      "Heat a pan with butter or oil and cook the assembled fish bread on both sides until golden brown and crispy.",
      "Cut the fish bread into halves or quarters and serve hot with a side of ketchup or chutney.",
    ],
    video: "https://www.youtube.com/embed/KlHOUTWyPsY",
  },
  "Muradabadi Chicken": {
    title: "Muradabadi Chicken",
    image:
      "https://e1.pxfuel.com/desktop-wallpaper/143/352/desktop-wallpaper-chicken-biryani-biryani.jpg",
    description:
      "  Muradabadi Chicken is a flavorful and aromatic dish that originates from the city of Muradabad in Uttar Pradesh, India. Known for its rich spices and tender chicken, this dish is a favorite at many family gatherings and special occasions.",
    ingredients: [
      "500g chicken (cut into pieces)",
      "2 onions (finely sliced)",
      "2 tomatoes (finely chopped)",
      "2 tablespoons of ginger-garlic paste",
      "1 teaspoon of turmeric powder",
      "1 teaspoon of red chili powder",
      "1 teaspoon of coriander powder",
      "1/2 teaspoon of garam masala",
      "1/2 teaspoon of cumin seeds",
      "2-3 green chilies (slit)",
      "Salt to taste",
      "1/4 cup yogurt (whisked)",
      "2 tablespoons of lemon juice",
      "Fresh coriander leaves (for garnish)",
      "3 tablespoons of oil or ghee",
    ],
    steps: [
      "In a large bowl, mix the chicken pieces with turmeric powder, red chili powder, salt, and lemon juice. Let it marinate for 30 minutes.",
      "Heat oil or ghee in a deep pan and add cumin seeds. Let them splutter.",
      "Add the sliced onions and sauté until they turn golden brown.",
      "Add the ginger-garlic paste and sauté for another 2-3 minutes.",
      "Add the marinated chicken to the pan and cook on medium heat until the chicken starts to brown.",
      "Add the chopped tomatoes, coriander powder, and green chilies. Mix well and cook until the tomatoes turn soft.",
      "Reduce the heat and add the whisked yogurt to the chicken. Stir continuously to prevent curdling.",
      "Cover the pan and let the chicken simmer on low heat until it is fully cooked and tender.",
      "Once the chicken is cooked, sprinkle garam masala over the dish and give it a final stir.",
      "Garnish with fresh coriander leaves and serve hot with naan, roti, or rice.",
    ],
    video: "https://www.youtube.com/embed/0wXU8OQftUk",
  },
  "Lemon Mint Juice": {
    title: "Lemon Mint Juice",
    image:
      "https://images.pexels.com/photos/1187766/pexels-photo-1187766.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description:
      "Lemon Mint Juice is a refreshing and tangy drink perfect for hot summer days. This invigorating beverage combines the zesty flavor of lemons with the coolness of mint, making it a delightful treat for any time of the day.",
    ingredients: [
      "2 large lemons (juiced)",
      "1/4 cup fresh mint leaves",
      "2 tablespoons of sugar (adjust to taste)",
      "1/4 teaspoon black salt (optional)",
      "2 cups cold water",
      "Ice cubes",
      "Mint sprigs and lemon slices for garnish",
    ],
    steps: [
      "In a blender, add fresh mint leaves and a tablespoon of water. Blend until you have a smooth paste.",
      "In a large pitcher, combine the lemon juice, mint paste, sugar, and black salt. Stir well until the sugar is fully dissolved.",
      "Add cold water to the pitcher and stir to combine.",
      "Add ice cubes to the pitcher to chill the juice.",
      "Pour the lemon mint juice into glasses.",
      "Garnish each glass with a sprig of mint and a slice of lemon.",
      "Serve immediately and enjoy the refreshing drink.",
    ],
    video: "https://www.youtube.com/embed/DVYFj_8kYpY",
  },
  "Amla Juice": {
    title: "Amla Juice",
    image:
      "https://magadhtoday.com/wp-content/uploads/2023/09/amla-juice-benefits-for-females.webp",
    description:
      " Amla Juice is a nutritious and rejuvenating drink made from Indian gooseberries (amla). Rich in vitamin C and antioxidants, this juice boosts immunity and promotes overall health. It's a perfect choice for a daily health tonic.",
    ingredients: [
      "4-5 fresh amla (Indian gooseberries)",
      "1-2 tablespoons honey or sugar (optional)",
      "1/4 teaspoon black salt (optional)",
      "1/2 teaspoon ginger juice (optional)",
      "2 cups water",
      "Ice cubes (optional)",
      "Mint leaves for garnish",
    ],
    steps: [
      "Wash the amla thoroughly and cut them into small pieces, removing the seeds.",
      "Add the amla pieces to a blender along with 1/2 cup of water. Blend until smooth.",
      "Strain the blended amla pulp through a fine sieve or cheesecloth to extract the juice.",
      "In a pitcher, mix the strained amla juice with the remaining water.",
      "Add honey or sugar, black salt, and ginger juice if desired. Stir well until everything is combined.",
      "Pour the amla juice into glasses, add ice cubes if you like, and garnish with mint leaves.",
      "Serve chilled and enjoy the health benefits.",
    ],
    video: "https://www.youtube.com/embed/VLWlRVACVN4",
  },
  "Black Tea": {
    title: "Black Tea",
    image:
      "https://images.pexels.com/photos/13032225/pexels-photo-13032225.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description:
      " Black Tea is a classic and invigorating beverage enjoyed worldwide. Known for its rich flavor and deep color, this simple yet satisfying drink is perfect for starting your day or taking a relaxing break.",
    ingredients: [
      "1 teaspoon loose black tea leaves or 1 black tea bag",
      "1 cup water",
      "Sugar or honey (optional)",
      "Lemon slices or mint leaves (optional for garnish)",
    ],
    steps: [
      "In a small pot, bring 1 cup of water to a rolling boil.",
      "Add the black tea leaves or tea bag to the boiling water.",
      "Let it simmer for 2-3 minutes, depending on your desired strength.",
      "If using loose tea leaves, strain the tea into a cup using a fine sieve.",
      "If using a tea bag, simply remove the bag after brewing.",
      "Add sugar or honey to taste, stirring until dissolved.",
      "Optionally, garnish with a slice of lemon or a few mint leaves.",
      "Serve hot and enjoy your refreshing cup of black tea.",
    ],
    video: "https://www.youtube.com/embed/Ntl6aTCdf8c",
  },
  "Chiken Biryani": {
    title: "Chiken Biryani",
    image:
      "https://images.pexels.com/photos/12737817/pexels-photo-12737817.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description:
      "Chicken Biryani is a flavorful and aromatic dish that blends tender chicken with fragrant basmati rice and a rich blend of spices. This classic Indian dish is perfect for special occasions or a sumptuous family meal.",
    ingredients: [
      "For the Chicken Marinade:",
      "500g chicken (cut into pieces)",
      "1/2 cup yogurt",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "Salt to taste",
      "For the Biryani:",
      "2 cups basmati rice (soaked for 30 minutes)",
      "2 large onions (thinly sliced)",
      "2 tomatoes (chopped)",
      "2-3 green chilies (slit)",
      "1/2 cup fresh mint leaves",
      "1/2 cup fresh coriander leaves",
      "2 tablespoons ghee or oil",
      "4-5 cloves",
      "2-3 cardamom pods",
      "1 cinnamon stick",
      "1 bay leaf",
      "1 teaspoon cumin seeds",
      "1/4 teaspoon saffron threads (soaked in 2 tablespoons of warm milk)",
      "Salt to taste",
      "Water as needed",
    ],

    steps: [
      "In a large bowl, mix the chicken pieces with yogurt, ginger-garlic paste, turmeric powder, red chili powder, garam masala, and salt.",
      "Cover and marinate for at least 1 hour (preferably overnight).",
      "In a large pot, bring water to a boil. Add soaked basmati rice, salt, and cook until the rice is 70% cooked. Drain and set aside.",
      "In a deep pan, heat ghee or oil. Add cloves, cardamom pods, cinnamon stick, bay leaf, and cumin seeds. Sauté until fragrant.",
      "Add the sliced onions and cook until golden brown. Add the chopped tomatoes and cook until soft.",
      "Add the marinated chicken and cook until the chicken is sealed and begins to brown.",
      "Lower the heat and layer the partially cooked rice over the chicken.",
      "Sprinkle fresh mint leaves, coriander leaves, and saffron milk over the rice.",
      "Cover the pan with a tight-fitting lid and cook on low heat (dum) for 20-25 minutes until the chicken is fully cooked and the flavors meld together.",
      "Optionally, place a heavy object on the lid to ensure it stays closed during cooking.",
      "Gently fluff the biryani with a fork, mixing the layers slightly.",
      "Serve hot with raita, salad, or your favorite chutney.",
    ],
    video: "https://www.youtube.com/embed/YTYtKuLwl9U",
  },
  "Aloo Paratha": {
    title: "Aloo Paratha",
    image:
      "https://images.pexels.com/photos/12737919/pexels-photo-12737919.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description:
      "Aloo Paratha is a popular North Indian flatbread stuffed with a spiced potato filling. It's a comforting and satisfying dish that can be enjoyed for breakfast, lunch, or dinner, served with yogurt, pickle, or butter.",
    ingredients: [
      "2 cups whole wheat flour",
      "Water (as needed)",
      "Salt to taste",
      "1 tablespoon oil or ghee",
      "3 medium-sized potatoes (boiled and mashed)",
      "1 small onion (finely chopped)",
      "2 green chilies (finely chopped)",
      "1 teaspoon ginger (grated)",
      "1/2 teaspoon cumin seeds",
      "1/2 teaspoon red chili powder",
      "1/2 teaspoon turmeric powder",
      "1/2 teaspoon garam masala",
      "1/2 teaspoon dry mango powder (amchur) Salt to taste",
      "Fresh coriander leaves (finely chopped)",
      "Ghee or oil (for cooking)",
    ],
    steps: [
      "In a large bowl, mix the whole wheat flour, salt, and a tablespoon of oil or ghee.",
      "Gradually add water and knead the mixture into a soft, smooth dough. Cover and let it rest for 15-20 minutes.",
      "In a mixing bowl, combine the mashed potatoes, chopped onion, green chilies, grated ginger, cumin seeds, red chili powder, turmeric powder, garam masala, dry mango powder, and salt. Mix well.",
      "Add chopped coriander leaves to the mixture and mix thoroughly.",
      "Divide the dough into equal-sized balls. Roll each ball into a small disc.",
      "Place a portion of the potato filling in the center of the disc. Gather the edges of the dough and seal the filling inside.",
      "Gently roll the filled dough ball into a flat, round paratha.",
      "Heat a tawa or flat griddle on medium heat. Place the rolled paratha on the tawa.",
      "Cook for 1-2 minutes on one side, then flip. Apply ghee or oil on the cooked side and flip again. Apply ghee or oil on the other side as well.",
      "Cook until both sides are golden brown and slightly crisp.",
      "Serve hot with yogurt, pickle, or a dollop of butter.",
    ],
    video: "https://www.youtube.com/embed/dBXiHx11niM",
  },
  "Samosa": {
    title: "Samosa",
    image:
      "https://images.pexels.com/photos/4449068/pexels-photo-4449068.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description:
      "Samosa is a popular Indian snack made of crispy pastry filled with a spiced potato mixture. These triangular pastries are deep-fried to golden perfection and are perfect as a tea-time snack or appetizer, served with chutney or sauce.",
    ingredients: [
      "2 cups all-purpose flour (maida)",
      "1/4 cup ghee or oil",
      "Salt to taste",
      "Water (as needed)",
      "4 medium-sized potatoes (boiled and mashed)",
      "1/2 cup green peas (optional)",
      "1 small onion (finely chopped)",
      "2 green chilies (finely chopped)",
      "1 teaspoon ginger (grated)",
      "1/2 teaspoon cumin seeds",
      "1/2 teaspoon mustard seeds",
      "1/2 teaspoon turmeric powder",
      "1/2 teaspoon red chili powder",
      "1/2 teaspoon garam masala",
      "1/2 teaspoon dry mango powder (amchur)",
      "Salt to taste",
      "Fresh coriander leaves (finely chopped)",
      "Oil for frying",
    ],
    steps: [
      "In a large bowl, mix the all-purpose flour, salt, and ghee or oil.",
      "Gradually add water and knead into a stiff dough. Cover with a damp cloth and let it rest for 30 minutes.",
      "Heat oil in a pan and add cumin seeds and mustard seeds. Let them splutter.",
      "Add the chopped onion, green chilies, and grated ginger. Sauté until the onions turn golden brown.",
      "Add turmeric powder, red chili powder, garam masala, and salt. Mix well.",
      "Add the mashed potatoes and green peas (if using). Mix thoroughly to combine the spices with the potatoes.",
      "Stir in dry mango powder and chopped coriander leaves. Set aside to cool.",
      "Divide the dough into equal-sized balls. Roll each ball into a flat oval shape and cut it in half to form two semi-circles.",
      "Take one semi-circle and fold it into a cone shape, sealing the edge with a little water.",
      "Fill the cone with the potato mixture and seal the top edge to form a triangular samosa. Repeat with the remaining dough and filling.",
      "Heat oil in a deep frying pan over medium heat.",
      "Fry the samosas in batches until they are golden brown and crisp.",
      "Drain on paper towels to remove excess oil.",
      "Serve hot with mint chutney, tamarind chutney, or ketchup.",
    ],
    video: "https://www.youtube.com/embed/HCyalu9KMIs",
  },
  "Butter Chicken": {
    title: "Butter Chicken",
    image: "https://wallpaperaccess.com/full/5912737.jpg",
    description:
      " Butter Chicken, also known as Murgh Makhani, is a beloved Indian dish made with tender chicken simmered in a rich and creamy tomato-based gravy. This dish is famous for its smooth texture, balanced spices, and the luxurious taste of butter and cream, making it a favorite in Indian cuisine.",
    ingredients: [
      "For the Chicken Marinade:",
      "500g boneless chicken (cut into cubes)",
      "1/2 cup yogurt",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon garam masala",
      "Salt to taste",
      "1 tablespoon lemon juice",
      "For the Gravy: ",
      "2 tablespoons butter",
      "1 tablespoon oil",
      "2 large onions (finely chopped)",
      "2 large tomatoes (pureed)",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1/2 teaspoon garam masala",
      "1/4 cup fresh cream",
      "1/4 cup cashew paste (optional)",
      "Salt to taste",
      "1 tablespoon honey or sugar (optional)",
      "Fresh coriander leaves (for garnish)",
    ],
    steps: [
      "In a large bowl, mix the chicken cubes with yogurt, ginger-garlic paste, red chili powder, turmeric powder, garam masala, salt, and lemon juice.",
      "over and marinate for at least 1 hour (preferably overnight) in the refrigerator.",
      "Heat oil in a pan and add the marinated chicken. Cook on medium heat until the chicken is cooked through and slightly charred. Set aside.",
      "In the same pan, add butter and let it melt. Add finely chopped onions and sauté until golden brown.",
      "Add ginger-garlic paste and sauté until the raw smell disappears.",
      "Add the pureed tomatoes, red chili powder, turmeric powder, cumin powder, coriander powder, and salt. Cook until the oil starts to separate from the masala.",
      "Add the cooked chicken pieces to the gravy and mix well.",
      "Stir in the fresh cream and cashew paste (if using), and cook for a few more minutes on low heat.",
      "Adjust the seasoning with honey or sugar if needed, and add a little water if the gravy is too thick.",
      "Garnish with fresh coriander leaves and a drizzle of cream.",
      "Serve hot with naan, roti, or basmati rice",
    ],
    video: "https://www.youtube.com/embed/JxSwBpEiYeQ",
  },
};
